name: Xcode - Build and Analyze

on:
  workflow_dispatch:

jobs:
  build:
    name: Clean
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Default Scheme
        run: |
          xcodebuild clean -scheme Knobby -q -json
